// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_KEYBOARD2_H
#define _UI_COMP_KEYBOARD2_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Keyboard2
#define UI_COMP_KEYBOARD2_KEYBOARD2 0
#define _UI_COMP_KEYBOARD2_NUM 1
lv_obj_t * ui_Keyboard2_create(lv_obj_t * comp_parent);
void ui_event_comp_Keyboard2_Keyboard2(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
