// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"


void ui_event_comp_Keyboard2_Keyboard2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_Keyboard2 = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(comp_Keyboard2[UI_COMP_KEYBOARD2_KEYBOARD2],  ui_password);
    }
    if(event_code == LV_EVENT_CLICKED) {
        key_yes_event(e);
    }
}

// COMPONENT Keyboard2

lv_obj_t * ui_Keyboard2_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Keyboard2;
    cui_Keyboard2 = lv_keyboard_create(comp_parent);
    lv_obj_set_width(cui_Keyboard2, 315);
    lv_obj_set_height(cui_Keyboard2, 123);
    lv_obj_set_x(cui_Keyboard2, 0);
    lv_obj_set_y(cui_Keyboard2, 55);
    lv_obj_set_align(cui_Keyboard2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_Keyboard2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_Keyboard2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_KEYBOARD2_NUM);
    children[UI_COMP_KEYBOARD2_KEYBOARD2] = cui_Keyboard2;
    lv_obj_add_event_cb(cui_Keyboard2, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Keyboard2, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_Keyboard2, ui_event_comp_Keyboard2_Keyboard2, LV_EVENT_ALL, children);
    ui_comp_Keyboard2_create_hook(cui_Keyboard2);
    return cui_Keyboard2;
}

