// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"


void ui_event_comp_Button1_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_Button1 = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        wifi_connect(e);
    }
}

// COMPONENT Button1

lv_obj_t * ui_Button1_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Button1;
    cui_Button1 = lv_btn_create(comp_parent);
    lv_obj_set_width(cui_Button1, 100);
    lv_obj_set_height(cui_Button1, 34);
    lv_obj_set_x(cui_Button1, 58);
    lv_obj_set_y(cui_Button1, -37);
    lv_obj_set_align(cui_Button1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_Button1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_Button1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(cui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(cui_Button1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_text_opa(cui_Button1, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BUTTON1_NUM);
    children[UI_COMP_BUTTON1_BUTTON1] = cui_Button1;
    lv_obj_add_event_cb(cui_Button1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Button1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_Button1, ui_event_comp_Button1_Button1, LV_EVENT_ALL, children);
    ui_comp_Button1_create_hook(cui_Button1);
    return cui_Button1;
}

