// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_wificonnect_screen_init(void)
{
    ui_wificonnect = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_wificonnect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_wificonnect);
    lv_obj_set_width(ui_Panel1, 320);
    lv_obj_set_height(ui_Panel1, 240);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, -3);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_password = lv_textarea_create(ui_wificonnect);
    lv_obj_set_width(ui_password, 231);
    lv_obj_set_height(ui_password, LV_SIZE_CONTENT);    /// 39
    lv_obj_set_x(ui_password, -35);
    lv_obj_set_y(ui_password, -38);
    lv_obj_set_align(ui_password, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_password, 16);
    lv_textarea_set_placeholder_text(ui_password, "密码");
    lv_textarea_set_one_line(ui_password, true);
    lv_obj_set_style_text_align(ui_password, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_password, &ui_font_ali, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_set_style_text_align(ui_password, LV_TEXT_ALIGN_AUTO, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_password, &ui_font_ali, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_wificonnect);
    lv_obj_set_width(ui_Keyboard1, 320);
    lv_obj_set_height(ui_Keyboard1, 120);
    lv_obj_set_x(ui_Keyboard1, 0);
    lv_obj_set_y(ui_Keyboard1, 55);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Keyboard1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Keyboard1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_Panel1, ui_event_Panel1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_password, ui_event_password, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);
    uic_wifi_password = ui_password;

}
